#!/usr/bin/env python3
"""
Injects the custom keyboard's native Android files into an android/ folder
that was just generated by `flutter create --platforms=android .`

Usage:
    python3 scripts/apply_keyboard_files.py com.example.keyboard_app

Safe to re-run (idempotent) — it won't duplicate the <service> block if
it's already present in AndroidManifest.xml.
"""
import sys
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NATIVE = ROOT / "keyboard_native"


def main():
    package = sys.argv[1] if len(sys.argv) > 1 else "com.example.keyboard_app"
    package_path = package.replace(".", "/")

    android_main = ROOT / "android" / "app" / "src" / "main"
    kotlin_dir = android_main / "kotlin" / package_path
    xml_dir = android_main / "res" / "xml"
    manifest_path = android_main / "AndroidManifest.xml"

    if not android_main.exists():
        sys.exit(
            "ERROR: android/app/src/main not found. "
            "Run `flutter create --platforms=android .` first."
        )

    # 1. Copy Kotlin sources (overwrites the generated MainActivity.kt on purpose)
    kotlin_dir.mkdir(parents=True, exist_ok=True)
    for kt_file in (NATIVE / "kotlin").glob("*.kt"):
        dest = kotlin_dir / kt_file.name
        content = kt_file.read_text().replace(
            "package com.example.keyboard_app", f"package {package}"
        )
        dest.write_text(content)
        print(f"wrote {dest}")

    # 2. Copy method.xml
    xml_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy(NATIVE / "xml" / "method.xml", xml_dir / "method.xml")
    print(f"wrote {xml_dir / 'method.xml'}")

    # 3. Patch AndroidManifest.xml with the <service> block
    manifest = manifest_path.read_text()
    if "CustomKeyboardService" in manifest:
        print("AndroidManifest.xml already patched, skipping.")
        return

    service_block = f'''        <service
            android:name=".CustomKeyboardService"
            android:label="Professional Keyboard"
            android:permission="android.permission.BIND_INPUT_METHOD"
            android:exported="true">
            <intent-filter>
                <action android:name="android.view.InputMethod" />
            </intent-filter>
            <meta-data
                android:name="android.view.im"
                android:resource="@xml/method" />
        </service>
'''
    if "</application>" not in manifest:
        sys.exit("ERROR: </application> tag not found in AndroidManifest.xml")

    manifest = manifest.replace("</application>", service_block + "    </application>")
    manifest_path.write_text(manifest)
    print(f"patched {manifest_path}")


if __name__ == "__main__":
    main()
